stages:
    - test
    - build
    - publish

variables: 
    DOCKER_REGISTRY: 031648642715.dkr.ecr.us-east-1.amazonaws.com
    AWS_DEFAULT_REGION: us-east-1
    APP_NAME: sample-multicontainer-app-client
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

build:
    stage: build
    image:
        name: docker:docker:23.0.0-rc.1-cli
    services:
        - docker:23.0.0-rc.1-dind
    before_script:
        - apk add --no-cache curl jq python3 py3-pip
        - pip install awscli
        - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
        - aws --version # print into logs the version of aws cli
        - docker info # print docker 
        - docker --version # verify docker installed by printing the version
    script:
        - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID -f ./client/Dockerfile.dev ./client
        - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID


