stages: 
    - test # nothing happens at this stage yet
    - build # build docker images and push to docker registry

test:
    stage: test
    image: docker:23.0.0-rc.1-cli
    services:
        - docker:23.0.0-rc.1-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        #- docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./client/Dockerfile.dev ./client
        - docker build -t testimage:testtag -f ./client/Dockerfile.dev ./client
    script: 
        #- docker run $IMAGE_NAME:$IMAGE_TAG npm test -- --coverage
        - docker run testimage:testtag npm test -- --coverage

#build_images:
#    image: docker:23.0.0-rc.1-cli
#    services:
#        - docker:23.0.0-rc.1-cli-dind
#    variables:
#        DOCKER_TLS_CERTDIR: "/certs"
#    before_script:
#        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY_NAME <- image registry account needed
#    script: 
#        - docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./client/Dockerfile.dev ./client
#        - docker push $IMAGE_NAME:$IMAGE_TAG
